In [64]:
import pandas as pd
import numpy as np

In [65]:
df = pd.read_excel('../data/Dataset.xlsx')
df.head()

,ï»¿Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [66]:
import os
print(os.getcwd())

c:\Users\Nitsat\Desktop\Customer_Retention_Project\notebooks

In [67]:
import os
print(os.listdir('..'))

['dashboard', 'data', 'notebooks', 'presentation', 'processed', 'reports', 'sql', 'venv']

In [68]:
import os

print("Current:", os.getcwd())
print("One level up:", os.listdir('..'))
print("Two levels up:", os.listdir('../..'))

Current: c:\Users\Nitsat\Desktop\Customer_Retention_Project\notebooks
One level up: ['dashboard', 'data', 'notebooks', 'presentation', 'processed', 'reports', 'sql', 'venv']
Two levels up: ['Arduino IDE.lnk', 'BetterTogetherSetup.exe', 'Claude.lnk', 'Comet.lnk', 'CRYPTO', 'Customer_Retention_Project', 'desktop.ini', 'Docker Desktop.lnk', 'EEG_Projet', 'Excel 2013.lnk', 'FILES', 'FPGA_Projects', 'from adress.docx', 'GCC PROPERTY TAX BILL', 'GMR PHOTOS', 'Kyocera TASKalfa 1800 - Shortcut.lnk', 'LETTERS AND DOCS', 'LM Studio.lnk', 'Microsoft Edge.lnk', 'My stuff', 'n8n-data', 'NAVARATRI 2019', 'NSK VASAVI ESTATES.rar', 'OLD PC FILES', 'OpenOffice 4.1.15 (en-US) Installation Files', 'PATTA', 'Qneuro', 'SATHISH(Photos and Videos)', 'SATHVIK FILES', 'This PC - Shortcut.lnk', 'TRUECLOUD.lnk', 'Word 2013.lnk', 'Zoom Workplace.lnk']

In [69]:
df['Review Rating'] = df['Review Rating'].fillna(
    df['Review Rating'].median()
)

In [70]:
df['Frequency of Purchases'] = df['Frequency of Purchases'].replace({
    'Bi-Weekly':'Fortnightly',
    'Every 3 Months':'Quarterly'
})

In [71]:
df['Frequency of Purchases'].unique()

<StringArray>
['Fortnightly', 'Weekly', 'Annually', 'Quarterly', 'Monthly']
Length: 5, dtype: str

In [72]:
frequency_map = {
    'Weekly':5,
    'Fortnightly':4,
    'Monthly':3,
    'Quarterly':2,
    'Annually':1
}

df['Frequency Score'] = df['Frequency of Purchases'].map(frequency_map)

In [73]:
df[['Frequency of Purchases','Frequency Score']].head(10)

  Frequency of Purchases  Frequency Score
0            Fortnightly                4
1            Fortnightly                4
2                 Weekly                5
3                 Weekly                5
4               Annually                1
5                 Weekly                5
6              Quarterly                2
7                 Weekly                5
8               Annually                1
9              Quarterly                2

In [74]:
df['Frequency of Purchases'].unique()

<StringArray>
['Fortnightly', 'Weekly', 'Annually', 'Quarterly', 'Monthly']
Length: 5, dtype: str

In [75]:
df[['Frequency of Purchases','Frequency Score']].head(10)

  Frequency of Purchases  Frequency Score
0            Fortnightly                4
1            Fortnightly                4
2                 Weekly                5
3                 Weekly                5
4               Annually                1
5                 Weekly                5
6              Quarterly                2
7                 Weekly                5
8               Annually                1
9              Quarterly                2

In [76]:
df['Subscription Score'] = np.where(
    df['Subscription Status'] == 'Yes',
    1,
    0
)

In [77]:
df[['Subscription Status','Subscription Score']].head(10)

  Subscription Status  Subscription Score
0                 Yes                   1
1                 Yes                   1
2                 Yes                   1
3                 Yes                   1
4                 Yes                   1
5                 Yes                   1
6                 Yes                   1
7                 Yes                   1
8                 Yes                   1
9                 Yes                   1

In [78]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

df[['Previous Purchases_N',
    'Frequency Score_N',
    'Review Rating_N']] = scaler.fit_transform(
        df[['Previous Purchases',
            'Frequency Score',
            'Review Rating']]
)

In [79]:
df[['Previous Purchases_N',
    'Frequency Score_N',
    'Review Rating_N']].head()

   Previous Purchases_N  Frequency Score_N  Review Rating_N
0              0.265306               0.75             0.24
1              0.020408               0.75             0.24
2              0.448980               1.00             0.24
3              0.979592               1.00             0.40
4              0.612245               0.00             0.08

In [80]:
df['Subscription Score'] = np.where(
    df['Subscription Status'] == 'Yes',
    1,
    0
)

In [81]:
df[['Subscription Status','Subscription Score']].head()

  Subscription Status  Subscription Score
0                 Yes                   1
1                 Yes                   1
2                 Yes                   1
3                 Yes                   1
4                 Yes                   1

In [82]:
df['Loyalty Score V1'] = (
    0.4 * df['Previous Purchases_N']
    + 0.3 * df['Frequency Score_N']
    + 0.2 * df['Subscription Score']
    + 0.1 * df['Review Rating_N']
)

In [83]:
df[['Loyalty Score V1']].describe()

       Loyalty Score V1
count       3900.000000
mean           0.450425
std            0.182214
min            0.016000
25%            0.319041
50%            0.444235
75%            0.575740
max            0.984000

In [84]:
df[['Loyalty Score V1']].head(10)

   Loyalty Score V1
0          0.555122
1          0.457163
2          0.703592
3          0.931837
4          0.452898
5          0.622122
6          0.694837
7          0.674939
8          0.261143
9          0.391490

In [85]:
df['Loyalty Band'] = pd.qcut(
    df['Loyalty Score V1'],
    q=4,
    labels=['Low','Medium','High','Very High']
)

In [86]:
df['Loyalty Band'].value_counts()

Loyalty Band
Low          975
Medium       975
High         975
Very High    975
Name: count, dtype: int64

In [87]:
df[['Purchase Amount_N']] = scaler.fit_transform(
    df[['Purchase Amount (USD)']]
)

In [88]:
df[['Purchase Amount (USD)','Purchase Amount_N']].head()

   Purchase Amount (USD)  Purchase Amount_N
0                     53             0.4125
1                     64             0.5500
2                     73             0.6625
3                     90             0.8750
4                     49             0.3625

In [89]:
df['Loyalty Score V2'] = (
    0.5 * df['Previous Purchases_N']
    + 0.3 * df['Purchase Amount_N']
    + 0.2 * df['Review Rating_N']
)

In [90]:
df[['Loyalty Score V1',
    'Loyalty Score V2']].describe()

       Loyalty Score V1  Loyalty Score V2
count       3900.000000       3900.000000
mean           0.450425          0.497645
std            0.182214          0.182909
min            0.016000          0.029954
25%            0.319041          0.365291
50%            0.444235          0.496827
75%            0.575740          0.629739
max            0.984000          0.977000

In [91]:
df['Promo Dependency Score'] = (
    (df['Discount Applied'] == 'Yes').astype(int)
    +
    (df['Promo Code Used'] == 'Yes').astype(int)
)

In [92]:
def promo_segment(x):
    if x == 2:
        return 'High'
    elif x == 1:
        return 'Medium'
    else:
        return 'Low'

df['Promo Dependency Level'] = (
    df['Promo Dependency Score']
    .apply(promo_segment)
)

In [93]:
df['Promo Dependency Level'].value_counts()

Promo Dependency Level
Low     2223
High    1677
Name: count, dtype: int64

In [94]:
df[['Loyalty Score V1',
    'Loyalty Score V2']].describe()

       Loyalty Score V1  Loyalty Score V2
count       3900.000000       3900.000000
mean           0.450425          0.497645
std            0.182214          0.182909
min            0.016000          0.029954
25%            0.319041          0.365291
50%            0.444235          0.496827
75%            0.575740          0.629739
max            0.984000          0.977000

In [95]:
df['Promo Dependency Level'].value_counts()

Promo Dependency Level
Low     2223
High    1677
Name: count, dtype: int64

In [96]:
df['Customer Value Score'] = (
    df['Purchase Amount (USD)']
    *
    df['Previous Purchases']
)

In [97]:
df[['Purchase Amount (USD)',
    'Previous Purchases',
    'Customer Value Score']].head()

   Purchase Amount (USD)  Previous Purchases  Customer Value Score
0                     53                  14                   742
1                     64                   2                   128
2                     73                  23                  1679
3                     90                  49                  4410
4                     49                  31                  1519

In [98]:
df['Value Tier'] = pd.qcut(
    df['Customer Value Score'],
    q=4,
    labels=[
        'Bronze',
        'Silver',
        'Gold',
        'Platinum'
    ]
)

In [99]:
df['Value Tier'].value_counts()

Value Tier
Silver      977
Bronze      975
Platinum    975
Gold        973
Name: count, dtype: int64

In [100]:
def customer_segment(row):

    if (
        row['Value Tier'] == 'Platinum'
        and
        row['Promo Dependency Level'] == 'Low'
    ):
        return 'VIP Loyalist'

    elif (
        row['Promo Dependency Level'] == 'High'
    ):
        return 'Bargain Hunter'

    elif (
        row['Value Tier'] in ['Gold', 'Silver']
    ):
        return 'Growth Customer'

    else:
        return 'Low Engagement'


df['Customer Segment'] = df.apply(
    customer_segment,
    axis=1
)

In [101]:
df['Customer Segment'].value_counts()

Customer Segment
Bargain Hunter     1677
Growth Customer    1073
Low Engagement      584
VIP Loyalist        566
Name: count, dtype: int64

In [102]:
df.columns.tolist()

['ï»¿Customer ID',
 'Age',
 'Gender',
 'Item Purchased',
 'Category',
 'Purchase Amount (USD)',
 'Location',
 'Size',
 'Color',
 'Season',
 'Review Rating',
 'Subscription Status',
 'Shipping Type',
 'Discount Applied',
 'Promo Code Used',
 'Previous Purchases',
 'Payment Method',
 'Frequency of Purchases',
 'Frequency Score',
 'Subscription Score',
 'Previous Purchases_N',
 'Frequency Score_N',
 'Review Rating_N',
 'Loyalty Score V1',
 'Loyalty Band',
 'Purchase Amount_N',
 'Loyalty Score V2',
 'Promo Dependency Score',
 'Promo Dependency Level',
 'Customer Value Score',
 'Value Tier',
 'Customer Segment']

In [103]:
df.to_csv(
    '../processed/customer_features.csv',
    index=False
)

In [104]:
import os
print(os.getcwd())

c:\Users\Nitsat\Desktop\Customer_Retention_Project\notebooks

In [105]:
df = pd.read_excel('../data/Dataset.xlsx')

In [106]:
import os
print(os.listdir('..'))

['dashboard', 'data', 'notebooks', 'presentation', 'processed', 'reports', 'sql', 'venv']

In [107]:
df.to_csv('../processed/customer_features.csv', index=False)

In [108]:
import os
print(os.listdir('../processed'))

['customer_features.csv']

In [109]:
for col in df.columns:
    print(col)

ï»¿Customer ID
Age
Gender
Item Purchased
Category
Purchase Amount (USD)
Location
Size
Color
Season
Review Rating
Subscription Status
Shipping Type
Discount Applied
Promo Code Used
Previous Purchases
Payment Method
Frequency of Purchases

In [110]:
df.to_csv('../processed/customer_features.csv', index=False)

In [111]:
print(df.columns.tolist())

['ï»¿Customer ID', 'Age', 'Gender', 'Item Purchased', 'Category', 'Purchase Amount (USD)', 'Location', 'Size', 'Color', 'Season', 'Review Rating', 'Subscription Status', 'Shipping Type', 'Discount Applied', 'Promo Code Used', 'Previous Purchases', 'Payment Method', 'Frequency of Purchases']

In [112]:
df.columns = df.columns.str.replace('ï»¿', '', regex=False)

In [113]:
print(df.columns.tolist())

['Customer ID', 'Age', 'Gender', 'Item Purchased', 'Category', 'Purchase Amount (USD)', 'Location', 'Size', 'Color', 'Season', 'Review Rating', 'Subscription Status', 'Shipping Type', 'Discount Applied', 'Promo Code Used', 'Previous Purchases', 'Payment Method', 'Frequency of Purchases']

In [114]:
freq_map = {
    'Annually':1,
    'Quarterly':2,
    'Monthly':3,
    'Fortnightly':4,
    'Weekly':5
}

df['Frequency Score'] = df['Frequency of Purchases'].map(freq_map)

In [115]:
import numpy as np

df['Subscription Score'] = np.where(
    df['Subscription Status']=='Yes',
    1,
    0
)

In [116]:
df['Review Rating'] = df['Review Rating'].fillna(
    df['Review Rating'].median()
)

In [117]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

df[['Previous Purchases_N',
    'Frequency Score_N',
    'Review Rating_N']] = scaler.fit_transform(
    df[['Previous Purchases',
        'Frequency Score',
        'Review Rating']]
)

In [118]:
df['Loyalty Score V1'] = (
    0.4 * df['Previous Purchases_N']
    + 0.4 * df['Frequency Score_N']
    + 0.2 * df['Review Rating_N']
)

In [119]:
df['Loyalty Band'] = pd.qcut(
    df['Loyalty Score V1'],
    q=4,
    labels=['Low','Medium','High','Very High']
)

In [120]:
df['Promo Dependency Score'] = np.where(
    df['Promo Code Used']=='Yes',
    1,
    0
)

df['Promo Dependency Level'] = np.where(
    df['Promo Dependency Score']==1,
    'High',
    'Low'
)

In [121]:
df['Customer Value Score'] = (
    df['Purchase Amount (USD)']
    * df['Previous Purchases']
)

In [122]:
df['Value Tier'] = pd.qcut(
    df['Customer Value Score'],
    q=4,
    labels=['Bronze','Silver','Gold','Platinum']
)

In [123]:
def customer_segment(row):

    if row['Value Tier'] == 'Platinum':
        return 'VIP Loyalist'

    elif row['Promo Dependency Level'] == 'High':
        return 'Bargain Hunter'

    elif row['Value Tier'] in ['Gold','Silver']:
        return 'Growth Customer'

    else:
        return 'Low Engagement'

df['Customer Segment'] = df.apply(
    customer_segment,
    axis=1
)

In [124]:
print(df.columns.tolist())

['Customer ID', 'Age', 'Gender', 'Item Purchased', 'Category', 'Purchase Amount (USD)', 'Location', 'Size', 'Color', 'Season', 'Review Rating', 'Subscription Status', 'Shipping Type', 'Discount Applied', 'Promo Code Used', 'Previous Purchases', 'Payment Method', 'Frequency of Purchases', 'Frequency Score', 'Subscription Score', 'Previous Purchases_N', 'Frequency Score_N', 'Review Rating_N', 'Loyalty Score V1', 'Loyalty Band', 'Promo Dependency Score', 'Promo Dependency Level', 'Customer Value Score', 'Value Tier', 'Customer Segment']

In [125]:
df.to_csv('../processed/customer_features.csv', index=False)

In [126]:
df[['Customer Segment',
    'Value Tier',
    'Loyalty Band']].head()

  Customer Segment Value Tier Loyalty Band
0   Bargain Hunter     Silver       Medium
1   Bargain Hunter     Bronze       Medium
2   Bargain Hunter       Gold         High
3     VIP Loyalist   Platinum    Very High
4   Bargain Hunter       Gold          Low

In [127]:
for col in df.columns:
    print(col)

Customer ID
Age
Gender
Item Purchased
Category
Purchase Amount (USD)
Location
Size
Color
Season
Review Rating
Subscription Status
Shipping Type
Discount Applied
Promo Code Used
Previous Purchases
Payment Method
Frequency of Purchases
Frequency Score
Subscription Score
Previous Purchases_N
Frequency Score_N
Review Rating_N
Loyalty Score V1
Loyalty Band
Promo Dependency Score
Promo Dependency Level
Customer Value Score
Value Tier
Customer Segment